# Generated by Django 2.2.3 on 2019-07-24 08:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import info_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('description', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('img_url', models.ImageField(blank=True, null=True, upload_to=info_manager.models._category_image_path, verbose_name='Image')),
                ('ordering', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='If active, is visible')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('description', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('img_url', models.ImageField(blank=True, null=True, upload_to=info_manager.models._category_image_path, verbose_name='Image')),
                ('ordering', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='If active, is visible')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manager.Category')),
            ],
            options={
                'verbose_name': 'Info Item',
                'verbose_name_plural': 'Info Items',
                'ordering': ['ordering', 'name'],
            },
        ),
    ]
