# Generated by Django 2.2.2 on 2019-08-01 07:55

from django.db import migrations, models
import info_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('info_manager', '0002_auto_20190724_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to=info_manager.models._category_image_path, verbose_name='Immagine'),
        ),
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to=info_manager.models._category_image_path, verbose_name='Immagine'),
        ),
    ]
